### PR TITLE
long form of names for the institutional access widget

### PR DESCRIPTION
**Pull request by karenmajewicz**
Does this need to be changed elsewhere too?

### CODE REVIEW

**Comment by karenmajewicz** [comment]
See issue #335

**Comment by ewlarson** [comment]
The PR works, but I think we need to revisit the SVG icons here. They're not color consistent.

Screen Shot 2020-10-05 at 4 16 11 PM

I can't recall why this set of colorized icons ended up here, because they're missing the grayscale consistency of the icons I [committed to GeoBlacklight](https://github.com/geoblacklight/geoblacklight/commit/8828e3908fb8a2711ef9c273fbf3046d67b1d812#diff-d25fb5282c08ace801369d1e7034be20) about the same time last August.

**Comment by ewlarson** [comment]
Icons as committed to GBL.
Screen Shot 2020-10-05 at 4 35 35 PM

**Comment by ewlarson** [comment]
@karenmajewicz // Can you pull this latest commit and double-check things from your side?

My last commit here moves us back to using the [IcoMoon App](https://icomoon.io/app/#/select/image) to manage grayscale SVG icons. This lets us keep everything color consistent within the application. Also, I've removed all my older SVG code to use the blacklight_icon helper method in the app -- GBL now follows BL's patterns for SVG icons.

**Comment by karenmajewicz** [comment]
Your latest commit is working for me. All of the icons are now showing up grayscale, including Stanford and NYU. The Nebraska icon is still there as well.

**Pull request merged**
